### ISSUE TITLE
Expect errors to be thrown not returned

### ISSUE THREAD

**Issue by antonio-ivanovski** [mcking-07/safe-wrapper#1]
This library caught me off-guard, I was wondering how calls with `safe(myThrowingMethod())` would be wrapped in try-catch when the call of the throwing method is outside of the function closure. Then I noticed that errors in the example usage are being returned and not thrown. 

This makes the library not usable for any method calls outside of the ones that we have implemented. Think all of the JS methods, starting with `JSON.parse(...)`.

Because of this I have implemented my own safe call utility that maybe useful to be ported into this library or maybe help others.

My aim is to achieve the following API

```ts
const { data: parsedData, error: parseError } = safe(JSON.parse)(myJsonStr)
if (parseError) {
  // handle parse error
  throw new DocumentFailedToParseError({ cause: parseError })
}
// parsedData now we are sure that is parsed
doSomeWork(parsedData.myArray[1])
```

To achieve this I have implemented

```ts
type SafeCallFn = <TFn extends (...args: any) => any>(
    inputFn: TFn,
    thisArg?: any, // Optional parameter to specify the required `this` context
) => (
    ...args: Parameters<TFn>
) => ReturnType<TFn> extends Promise<Awaited<ReturnType<TFn>>>
    ? Promise<{ error: Error; data: never } | { data: Awaited<ReturnType<TFn>>; error: never }>
    : { error: Error; data: never } | { data: ReturnType<TFn>; error: never };

/**
 * Wrap the given function in a safe try-catch block (synchronous and asynchronous) and return the result as an object that contains the data or error.
 *
 * @param thisArg optional parameter to specify `this` where `this` has strict requirements for `this` context. Example for this is `crypto.subtle` functions.
 * @returns a function that takes the same parameters as the input function and returns an object with the data or error.
 */
export const safe: SafeCallFn = (fn, thisArg) => {
    return function (this: any, ...args) {
        try {
            const result = fn.apply(thisArg ?? this, args);
            if (result instanceof Promise) {
                return result
                    .then(
                        (data) =>
                            ({ data, error: undefined }) as { data: Awaited<ReturnType<typeof fn>>; error: never },
                    )
                    .catch((error) => ({ error, data: undefined }) as { error: Error; data: never });
            }
            return { data: result } as any;
        } catch (error) {
            return { error } as { error: Error; data: never };
        }
    };
};
```

**Comment by vjohansen** [comment]
I agree and it does not match the "[safe assignment operator proposal](https://github.com/arthurfiorette/proposal-safe-assignment-operator)" mentioned on the front page.

I think it is better to return an array like the proposal and avoid the destructuring to data and error you do.

In most cases the caller decides and the names and there is no need to see data and error all time. This is similar to the good design decision seen in React.useState

**Comment by LuKks** [comment]
https://github.com/LuKks/like-safe

```js
const safe = require('like-safe')

// Sync
const [res1, err1] = safe(sum)(2, 2) // => [4, null]
const [res2, err2] = safe(sum)(2, 'two') // => [null, Error]

// Async
const [res1, err1] = await safe(sumAsync)(2, 2) // => [4, null]
const [res2, err2] = await safe(sumAsync)(2, 'two') // => [null, Error]

// Shortcut for Promises
const [res1, err1] = await safe(sumAsync(2, 2)) // => [4, null]
const [res2, err2] = await safe(sumAsync(2, 'two')) // => [null, Error]
```

**Comment by mcking-07** [comment]
hey there, thank you for your feedback! the current design of `safe-wrapper` does lean towards a functional style of returning errors instead of throwing, allowing for downstream handling without requiring a `try-catch` block.

your approach using `safe(JSON.parse)(myJsonStr)` is interesting and something i considered early on, but i hesitated because it involves creating a new proxy function each time we wrap a function, which felt like an unnecessary overhead.

however, you've inspired an idea... we could allow directly wrapping the function definition itself. this way, we keep the code clean while maintaining compatibility with inbuilt functions and other cases where throwing behavior is expected.

```
// wrapping function at the definition level.
const safeAsync = safe(async () => {
  throw new Error('safeAsync error');
});

// wrapping function by creating a proxy.
const sync = () => {
  throw new Error('sync error');
}
const safeSync = safe(sync);

// wrapping a native function.
safe(JSON.parse)(string)
```

here, `safe` wraps these functions either by proxying them or directly at the definition, ensuring consistent error handling.

thanks again, i've gone ahead and implemented this!

**Comment by antonio-ivanovski** [comment]
> hey there, thank you for your feedback! the current design of `safe-wrapper` does lean towards a functional style of returning errors instead of throwing, allowing for downstream handling without requiring a `try-catch` block.
> 
> your approach using `safe(JSON.parse)(myJsonStr)` is interesting and something i considered early on, but i hesitated because it involves creating a new proxy function each time we wrap a function, which felt like an unnecessary overhead.
> 
> however, you've inspired an idea... we could allow directly wrapping the function definition itself. this way, we keep the code clean while maintaining compatibility with inbuilt functions and other cases where throwing behavior is expected.
> 
> ```
> // wrapping function at the definition level.
> const safeAsync = safe(async () => {
>   throw new Error('safeAsync error');
> });
> 
> // wrapping function by creating a proxy.
> const sync = () => {
>   throw new Error('sync error');
> }
> const safeSync = safe(sync);
> 
> // wrapping a native function.
> safe(JSON.parse)(string)
> ```
> 
> here, `safe` wraps these functions either by proxying them or directly at the definition, ensuring consistent error handling.
> 
> thanks again, i've gone ahead and implemented this!
> 

Glad that you have gone ahead and drawn inspiration from the initial proposal. I will check the implementation and will open PR for some edge cases (if not covered) while I was testing my implementation against a large codebase.

**Comment by mcking-07** [comment]
sure thing, @toteto! looking forward to your pr for any edge cases you find.
